mongo:
  image: mongo:2.6.10
  command: mongod --smallfiles
  ports:
   - "27017:27017"
api:
  build: .
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/siz
  ports:
   - "8080:8080"
   - "5005:5005"
  command: java  -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -jar target/api-0.0.1-SNAPSHOT.war --spring.profiles.active=dev,fixtures
  links:
   - mongo
   - videostripcreator
videostripcreator:
  image: videostrip
  environment:
    MONGO_URI: mongodb://mongo:27017/siz
  ports:
   - "5000:5000"
  links:
   - mongo
  command: ./videostrip-service.py
sizwebapp:
  image: sizwebapp
  environment:
      API_ENDPOINT: http://api:8080
  ports:
   - "1515:1515"
  links:
   - api
 
