mongo:
  image: mongo:2.6.10
  command: mongod --smallfiles
  ports:
   - "27017:27017"
api:
  build: .
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/siz
  ports:
   - "8080:8080"
   - "5005:5005"
  command: java -jar target/api-0.0.1-SNAPSHOT.war --spring.profiles.active=dev,fixtures
#  volumes:
#   - .:/var/www/siz-api
  links:
   - mongo

