server:
    port: 9000

liquibase:
    context: prod

spring:
    profiles:
        active: prod
    data:
        mongodb:
            uri: mongodb://localhost:27017
    thymeleaf:
        mode: XHTML
        cache: true
        
cloud:
  aws:
    stack:
      auto: false        

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: api

http:
    cache:
        timeToLiveInDays: 31


